app = "bottle-nexus-shopify-embed"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "3000"
  HOST = "0.0.0.0"
  SCOPES = "read_themes,write_themes"
  DATABASE_URL = "file:/data/dev.sqlite"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[mounts]]
  source = "data"
  destination = "/data"
