# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2d497d440db8520b84f0fc0eb290ee6e"
name = "Bottle Nexus Buy Button"
application_url = "https://bottle-nexus-shopify-embed.fly.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "read_themes,write_themes"

[auth]
redirect_urls = [ "https://bottle-nexus-shopify-embed.fly.dev/auth/callback" ]
